name: Metrics
on:
    schedule: [{ cron: '0 0 * * *' }] # every day at midnight
    workflow_dispatch:
    push: { branches: ['main'] }

jobs:
    habits:
        runs-on: ubuntu-latest
        environment:
            name: production
        permissions:
            contents: write
        steps:
            - uses: lowlighter/metrics@latest
              with:
                  filename: github-habits.svg
                  token: ${{ secrets.METRICS_TOKEN }}
                  committer_token: ${{ secrets.GITHUB_TOKEN }}
                  config_timezone: ${{ secrets.USER_TIMEZONE }} # Set timezone
                  user: scristobal
                  base: ''
                  template: repository
                  plugin_habits: yes
                  plugin_habits_facts: yes
                  plugin_habits_from: 500
                  plugin_habits_days: 60
                  plugin_habits_charts: yes
                  plugin_habits_trim: yes
                  plugin_languages: yes
                  plugin_languages_details: yes
                  #   plugin_languages_indepth: yes
                  plugin_sponsorships: yes
                  plugin_leetcode: yes
                  plugin_leetcode_user: scristobal
